const $=id=>document.getElementById(id);
const slots={a:null,b:null};
let version=0, building=false, resultURL=null, resultBlob=null, sequence=0, worker;
const pending=new Map(), loading={a:0,b:0};
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
try {
  worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});
  worker.onmessage=({data})=>{const p=pending.get(data.id);if(!p)return;pending.delete(data.id);data.error?p.reject(new Error(data.error)):p.resolve(data);};
  worker.onerror=()=>{for(const p of pending.values())p.reject(new Error('The GIF processor could not start. Reload the page from its website address.'));pending.clear();};
}catch{status('Open this app from its website address, rather than double-clicking the HTML file.',true);}
function task(data){return new Promise((resolve,reject)=>{if(!worker)return reject(new Error('The GIF processor is unavailable. Reload the website.'));const id=++sequence;pending.set(id,{resolve,reject});worker.postMessage({...data,id});});}
function size(n){return n>=1000000?`${(n/1000000).toFixed(2)} MB`:`${Math.round(n/1000)} KB`;}
function sync(){const ready=slots.a&&slots.b&&!loading.a&&!loading.b;$('build').disabled=!ready||building;$('swap').disabled=!ready||building;$('reset').disabled=(!slots.a&&!slots.b&&!loading.a&&!loading.b)||building;$('build').innerHTML=building?'Creating…':'Create split GIF <span>↗</span>';}
function invalidate(){version++;resultBlob=null;$('result').hidden=true;if(resultURL){URL.revokeObjectURL(resultURL);resultURL=null;}}
function render(key){const slot=slots[key],drop=$(`drop-${key}`);$(`image-${key}`).hidden=!slot;drop.querySelector('.placeholder').hidden=!!slot;drop.querySelector('.replace').hidden=!slot;if(slot){$(`image-${key}`).src=slot.url;$(`name-${key}`).textContent=slot.name;$(`meta-${key}`).textContent=`${slot.info.width}×${slot.info.height} · ${slot.info.frames} frames · ${size(slot.buffer.byteLength)}`;}else{$(`image-${key}`).removeAttribute('src');$(`name-${key}`).textContent=key==='a'?'The animation you want in chat':'The reveal after the first animation';$(`meta-${key}`).textContent='GIF · up to 20 MB';}$(`file-${key}`).value='';}
async function load(key,file){const token=++sequence;loading[key]=token;invalidate();sync();status(`Checking ${file.name}…`);try{if(file.size>20*1000000)throw new Error('Choose a GIF smaller than 20 MB.');const buffer=await file.arrayBuffer();const {info}=await task({type:'inspect',buffer});if(loading[key]!==token)return;if(slots[key])URL.revokeObjectURL(slots[key].url);slots[key]={buffer,info,name:file.name,url:URL.createObjectURL(new Blob([buffer],{type:'image/gif'}))};render(key);status(slots.a&&slots.b?'Both sides are ready. Create your split GIF.':'First side loaded. Choose the other GIF next.');}catch(error){if(loading[key]===token)status(error.message,true);}finally{if(loading[key]===token)loading[key]=0;sync();}}
for(const key of ['a','b']){const drop=$(`drop-${key}`);$(`file-${key}`).addEventListener('change',e=>{if(e.target.files[0])load(key,e.target.files[0]);});drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag');});drop.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');if(e.dataTransfer.files.length!==1){status('Drop one GIF in each side.',true);return;}load(key,e.dataTransfer.files[0]);});}
$('demo').onclick=async()=>{$('demo').disabled=true;try{const responses=await Promise.all(['discord-demo','browser-demo'].map(n=>fetch(new URL(`./assets/${n}.gif`,import.meta.url))));if(responses.some(r=>!r.ok))throw new Error('The demo files could not load. Please choose your own GIFs.');const blobs=await Promise.all(responses.map(r=>r.blob()));await Promise.all([load('a',new File([blobs[0]],'hello.gif')),load('b',new File([blobs[1]],'surprise.gif'))]);}catch(e){status(e.message,true);}finally{$('demo').disabled=false;}};
$('swap').onclick=()=>{[slots.a,slots.b]=[slots.b,slots.a];render('a');render('b');invalidate();status('Sides swapped. Create a new split GIF.');};
$('reset').onclick=()=>{invalidate();for(const key of ['a','b']){loading[key]=0;if(slots[key])URL.revokeObjectURL(slots[key].url);slots[key]=null;render(key);}sync();status('Choose two GIFs to get started, or try the demo.');};
$('repeats').onchange=()=>{invalidate();status('Timing updated. Create a new split GIF.');};
$('build').onclick=async()=>{if(!slots.a||!slots.b)return;building=true;sync();const current=version;status('Joining your GIFs…');try{const {buffer}=await task({type:'build',first:slots.a.buffer,second:slots.b.buffer,repeats:Number($('repeats').value)});if(version!==current)return;if(resultURL)URL.revokeObjectURL(resultURL);resultBlob=new Blob([buffer],{type:'image/gif'});resultURL=URL.createObjectURL(resultBlob);$('chat-preview').src=slots.a.url;$('chat-preview').alt='Simulation of the expected first-animation chat preview';$('browser-preview').src=resultURL;$('download').href=resultURL;$('open-result').href=resultURL;$('result-meta').textContent=`${size(buffer.byteLength)} · GIF`;$('result').hidden=false;status('Created. Check the live browser preview, then download and test in Discord.');$('result').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}catch(error){status(error.message,true);}finally{building=false;sync();}};
$('replay').onclick=()=>{if(resultBlob){const old=resultURL;resultURL=URL.createObjectURL(resultBlob);$('browser-preview').src=resultURL;$('download').href=resultURL;$('open-result').href=resultURL;if(old)URL.revokeObjectURL(old);}};
window.addEventListener('beforeunload',()=>{worker?.terminate();for(const s of Object.values(slots))if(s)URL.revokeObjectURL(s.url);if(resultURL)URL.revokeObjectURL(resultURL);});
