const $=id=>document.getElementById(id),slots={a:null,b:null},loading={a:0,b:0},pending=new Map();
let mode='gif',version=0,building=false,sequence=0,worker,resultBlob=null,resultURL=null,chatURL=null,reportURL=null;
const size=n=>n>=1e6?`${(n/1e6).toFixed(2)} MB`:`${Math.round(n/1000)} KB`;
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
try{worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});worker.onmessage=({data})=>{const p=pending.get(data.id);if(!p)return;pending.delete(data.id);data.error?p.reject(new Error(data.error)):p.resolve(data);};worker.onerror=()=>{for(const p of pending.values())p.reject(new Error('The processor stopped. Reload the website and try a smaller file.'));pending.clear();worker.terminate();worker=null;};}catch{status('Open this app from its website address so the local processor can start.',true);}
function task(data){return new Promise((resolve,reject)=>{if(!worker)return reject(new Error('The processor is unavailable. Reload the website.'));const id=++sequence;pending.set(id,{resolve,reject});worker.postMessage({...data,id});});}
function invalidate(){version++;resultBlob=null;$('result').hidden=true;for(const url of [resultURL,chatURL,reportURL])if(url)URL.revokeObjectURL(url);resultURL=chatURL=reportURL=null;}
function sync(){const busy=building||!!loading.a||!!loading.b,ready=slots.a&&slots.b&&!busy;$('build').disabled=!ready;$('swap').disabled=!ready||mode==='cover';$('reset').disabled=building||(!slots.a&&!slots.b&&!busy);$('demo').disabled=busy;for(const id of ['file-a','file-b'])$(id).disabled=building;for(const id of ['mode-gif','mode-cover'])$(id).disabled=busy;$('build').textContent=building?'Assembling…':'Create split GIF ↗';}
function setMode(next){if(mode===next)return;mode=next;invalidate();for(const key of ['gif','cover'])$(`mode-${key}`).setAttribute('aria-pressed',String(mode===key));$('cover-settings').hidden=mode!=='cover';$('intro-settings').hidden=mode==='cover';$('file-a').accept=mode==='cover'?'image/png,image/jpeg,image/webp,image/gif,.png,.jpg,.jpeg,.webp,.gif':'image/gif,.gif';$('a-title').textContent=mode==='cover'?'The still cover':'The chat side';$('a-prompt').textContent=mode==='cover'?'Drop a cover image':'Drop your first GIF';$('mode-description').textContent=mode==='cover'?'A single image frame for the chat preview. A blink, then your GIF in the browser.':'An animated chat preview. A different animation when the original opens.';$('loop').value=mode==='cover'?'once':'forever';if(slots.a?.kind==='image'&&mode==='gif'){URL.revokeObjectURL(slots.a.url);slots.a=null;}render('a');sync();status(mode==='cover'?'Choose a PNG, JPG, WebP, or GIF cover, then the reveal GIF.':'Choose two GIFs, or try the demo.');}
function render(key){const slot=slots[key],drop=$(`drop-${key}`);$(`image-${key}`).hidden=!slot;drop.querySelector('.placeholder').hidden=!!slot;drop.querySelector('.replace').hidden=!slot;if(slot){$(`image-${key}`).src=slot.url;$(`name-${key}`).textContent=slot.name;$(`meta-${key}`).textContent=`${slot.info.width}×${slot.info.height} · ${slot.kind==='image'?'STILL':slot.info.frames+' FRAMES'} · ${size(slot.buffer.byteLength)}`;}else{$(`image-${key}`).removeAttribute('src');$(`name-${key}`).textContent=key==='a'?(mode==='cover'?'The image shown in chat':'The animation shown in chat'):'The animation behind the cover';$(`meta-${key}`).textContent=key==='a'&&mode==='cover'?'PNG / JPG / WEBP / GIF · 20 MB':'GIF · 20 MB';}$(`file-${key}`).value='';}
async function imageInfo(blob){const bitmap=await createImageBitmap(blob);try{if(!bitmap.width||!bitmap.height||bitmap.width*bitmap.height>16777216)throw new Error('Choose an image smaller than 16 megapixels.');return {width:bitmap.width,height:bitmap.height,frames:1};}finally{bitmap.close();}}
async function load(key,file){const token=++sequence;loading[key]=token;invalidate();sync();status(`Reading ${file.name}…`);try{if(file.size>20e6)throw new Error('Choose a file smaller than 20 MB.');const buffer=await file.arrayBuffer(),bytes=new Uint8Array(buffer);const isGif=String.fromCharCode(...bytes.slice(0,6)).startsWith('GIF8');let kind='gif',info;if(isGif){({info}=await task({type:'inspect',buffer}));}else{if(key!=='a'||mode!=='cover')throw new Error(key==='b'?'The reveal must be a GIF.':'Choose a GIF, or switch to Still → GIF for images.');const png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78,jpg=bytes[0]===255&&bytes[1]===216,webp=String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';if(!png&&!jpg&&!webp)throw new Error('Choose a PNG, JPG, WebP, or GIF image.');kind='image';info=await imageInfo(file);}if(loading[key]!==token)return;if(slots[key])URL.revokeObjectURL(slots[key].url);slots[key]={kind,buffer,info,name:file.name,type:isGif?'image/gif':file.type,url:URL.createObjectURL(file)};render(key);status(slots.a&&slots.b?'Both sides are ready. Tune the experiment below, or create your GIF.':'Loaded. Choose the other side next.');}catch(e){if(loading[key]===token)status(e.message,true);}finally{if(loading[key]===token)loading[key]=0;sync();}}
for(const key of ['a','b']){const drop=$(`drop-${key}`);$(`file-${key}`).onchange=e=>{if(e.target.files[0])load(key,e.target.files[0]);};drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag');};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');if(building)return;if(e.dataTransfer.files.length!==1)return status('Drop one file in each side.',true);load(key,e.dataTransfer.files[0]);};}
$('mode-gif').onclick=()=>setMode('gif');$('mode-cover').onclick=()=>setMode('cover');
$('demo').onclick=async()=>{$('demo').disabled=true;try{const first=mode==='cover'?'cover-demo.png':'discord-demo.gif';const paths=[first,'browser-demo.gif'];const responses=await Promise.all(paths.map(n=>fetch(new URL(`./assets/${n}`,import.meta.url))));if(responses.some(r=>!r.ok))throw new Error('Demo files could not load. Choose your own files instead.');const blobs=await Promise.all(responses.map(r=>r.blob()));await Promise.all(blobs.map((b,i)=>load(i?'b':'a',new File([b],paths[i],{type:b.type}))));}catch(e){status(e.message,true);}finally{sync();}};
$('swap').onclick=()=>{[slots.a,slots.b]=[slots.b,slots.a];render('a');render('b');invalidate();status('Sides swapped. Create a new GIF.');};
$('reset').onclick=()=>{invalidate();for(const key of ['a','b']){loading[key]=0;if(slots[key])URL.revokeObjectURL(slots[key].url);slots[key]=null;render(key);}sync();status('Files cleared. Choose two sides to start again.');};
const settings=['repeats','cover-delay','fit','matte','palette','speed','loop','reveal-repeats','trails','note'];
for(const id of settings)$(id).addEventListener('input',()=>{invalidate();$('note-count').textContent=`${$('note').value.length}/140`;status('Settings changed. Create a new GIF to apply them.');});
async function coverPixels(){const image=await createImageBitmap(new Blob([slots.a.buffer],{type:slots.a.type}));try{const {width,height}=slots.b.info;if(width*height>4194304)throw new Error('For still covers, resize the reveal GIF to 4 megapixels or smaller.');const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.fillStyle=$('matte').value;ctx.fillRect(0,0,width,height);const ratio=($('fit').value==='crop'?Math.max:Math.min)(width/image.width,height/image.height),w=image.width*ratio,h=image.height*ratio;ctx.drawImage(image,(width-w)/2,(height-h)/2,w,h);return {coverPixels:ctx.getImageData(0,0,width,height).data.buffer,width,height};}finally{image.close();}}
function renderReport(report){$('result-meta').textContent=`${size(report.bytes)} / ${report.frames} FRAMES`;$('hex-header').textContent=report.headerHex;$('hex-transition').textContent=report.transitionHex;$('byte-summary').textContent=`${report.width} × ${report.height} canvas · transition at byte ${report.transitionOffset.toLocaleString()} (frame ${report.transitionFrame})`;$('decoded-note').textContent=report.comments.length?report.comments.join('\n'):'No comment block added.';const body=$('frame-rows');body.replaceChildren();for(const frame of report.frameTable.slice(0,100)){const row=document.createElement('tr');for(const v of [frame.frame,frame.kind,frame.delayMs+' ms','0x'+frame.offset.toString(16).toUpperCase()]){const cell=document.createElement('td');cell.textContent=v;row.append(cell);}body.append(row);}$('table-note').textContent=report.frames>100?`Showing the first 100 of ${report.frames} frames. Download the report for all frames.`:'All output frame descriptors are shown.';reportURL=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));$('report-download').href=reportURL;}
$('build').onclick=async()=>{if(!slots.a||!slots.b)return;building=true;sync();const current=version;status('Assembling the experiment locally…');try{const options={cover:mode==='cover',coverDelay:Number($('cover-delay').value),repeats:Number($('repeats').value),revealRepeats:Number($('reveal-repeats').value),loop:$('loop').value==='forever',palette:$('palette').value,speed:Number($('speed').value),trails:$('trails').checked,note:$('note').value};const pixels=options.cover?await coverPixels():{};const {buffer,chatBuffer,report}=await task({type:'build',first:slots.a.buffer,second:slots.b.buffer,...pixels,options});if(version!==current)return;for(const url of [resultURL,chatURL,reportURL])if(url)URL.revokeObjectURL(url);resultBlob=new Blob([buffer],{type:'image/gif'});resultURL=URL.createObjectURL(resultBlob);chatURL=URL.createObjectURL(new Blob([chatBuffer],{type:'image/gif'}));$('chat-preview').src=chatURL;$('browser-preview').src=resultURL;$('download').href=$('open-result').href=resultURL;$('result-explanation').textContent=options.cover?`One cover frame (${options.coverDelay} ms requested), then the reveal. ${options.loop?'The cover returns each time the whole file loops.':'Play once keeps the cover from returning; the file stops on its last frame.'} A brief flash is possible.`:`Intro, transition, then the reveal. ${options.loop?'The complete sequence loops.':'Playback stops on the last frame.'}`;renderReport(report);$('result').hidden=false;status('Ready. The browser preview below plays the actual generated file.');$('result').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}catch(e){status(e.message,true);}finally{building=false;sync();}};
$('replay').onclick=()=>{if(resultBlob){const old=resultURL;resultURL=URL.createObjectURL(resultBlob);$('browser-preview').src=resultURL;$('download').href=$('open-result').href=resultURL;if(old)URL.revokeObjectURL(old);}};
window.addEventListener('beforeunload',()=>{worker?.terminate();for(const s of Object.values(slots))if(s)URL.revokeObjectURL(s.url);for(const u of [resultURL,chatURL,reportURL])if(u)URL.revokeObjectURL(u);});
